name: Push to google app scripts

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
      - uses: actions/checkout@v2
      - uses: namaggarwal/clasp-token-action@v0.0.1
        with:
          client-id: ${{ secrets.CLIENT_ID }}
          client-secret: ${{ secrets.CLIENT_SECRET }}
          refresh-token: ${{ secrets.REFERSH_TOKEN }}
      - uses: actions/setup-node@v2
        with:
          node-version: 12
      - run: npm install -g @google/clasp
      - run: npm run push-to-app